"""sqlitemigrate

Revision ID: 25709bbec368
Revises: 
Create Date: 2019-03-12 18:48:54.827537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25709bbec368'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('code3l', sa.String(length=3), nullable=False),
    sa.Column('code2l', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_official', sa.String(length=200), nullable=False),
    sa.Column('flag_32', sa.String(length=200), nullable=False),
    sa.Column('flag_128', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.String(length=200), nullable=True),
    sa.Column('longitude', sa.String(length=200), nullable=True),
    sa.Column('zoom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Countries')
    # ### end Alembic commands ###
